version: 1.0.{build}

skip_branch_with_pr: true
branches:
  only:
    - master
    - dev
    - /release\/.*/

install:
  - git submodule update --init --recursive

build_script:
- ps: dotnet build -c Release