version: 1.0.{build}

image: Visual Studio 2019

skip_branch_with_pr: true
branches:
  only:
    - master
    - dev
    - /release\/.*/

install:
- ps: $IsMasterBranch = ($env:APPVEYOR_REPO_BRANCH -eq "master" -And -not $env:APPVEYOR_PULL_REQUEST_NUMBER)
- ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
- ps: $fileContent += $env:priv_key.Replace(' ', "`n")
- ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
- ps: Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent
- ps: Install-Product node 'LTS'
- git submodule -q update --init --recursive

build_script:
- dotnet build -c Release

test_script:
- dotnet test -c Release --no-build
- cd .\OrchardCore.LETS\Tests\Functional
- npm install
- npm run test

deploy_script:
- cd .\
- docker-compose build
- docker tag lets_orchardcorelets %DOCKER_USER%/lets_orchardcorelets:latest
- echo|set /p="%DOCKER_PASS%" | docker login --username %DOCKER_USER% --password-stdin
- docker push %DOCKER_USER%/lets_orchardcorelets:latest