version: 1.0.{build}

skip_branch_with_pr: true
branches:
  only:
    - master
    - dev
    - /release\/.*/

clone_script:
  - cmd: >-
      git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive

build_script:
- ps: dotnet build -c Release