version: '3.7'

services:
  lets.web:
    image: ${DOCKER_USERNAME}/letsweb
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80:80"
  watchtower:
      image: containrrr/watchtower
      container_name: watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      restart: always
      environment:
        - WATCHTOWER_NOTIFICATIONS=slack
        - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${WATCHTOWER_SLACK_WEBHOOK}