name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: textbook/git-checkout-submodule-action@2.1.1
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build -c Release LETS.Web\LETS.Web.csproj
    - name: Test
      run: dotnet test --no-restore --verbosity normal
