name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build -c Release LETS.Web/LETS.Web.csproj
    - name: Test
      run: dotnet test -c Release OrchardCore.LETS/Tests/LETS.Tests.csproj
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Functional tests
      working-directory: ./OrchardCore.LETS/Tests/Functional
      run: npm install && npm test
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        repository: ${{ secrets.DOCKER_USERNAME }}/letsweb
        dockerfile: LETS.Web/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest

